---
# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

linters:
  enable:
  - forbidigo
  - gosec
  - gosimple
  - godot
  - tagliatelle
  - revive
  - staticcheck
  - gocritic
  - depguard

linters-settings:

  depguard:
    rules:
      main:
        files:
        - "!**/*_test.go"
        allow:
        - $gostd
        - github.com/stv0g/go-rosenpass
        - github.com/open-quantum-safe/liboqs-go/oqs
        - github.com/pelletier/go-toml/v2
        - github.com/spf13/cobra
        - golang.org/x/crypto/blake2b
        - golang.org/x/crypto/chacha20poly1305
        - golang.org/x/exp/slog
        - golang.zx2c4.com/wireguard/wgctrl
        deny:
        - pkg: math/rand
          desc: Use cryptographic PRNG

  forbidigo:
    forbid:
    - ^os.Exit$
    - ^panic$
    - ^print(ln)?$
    - ^unsafe\.
    - ^log\.
    - ^fmt\.(Printf|Scanf|Sprintf|Sscanf)$
