---
# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

linters:
  enable:
  - forbidigo
  - gosec
  - gosimple
  - godot
  - tagliatelle
  - revive
  - staticcheck

linters-settings:

  forbidigo:
    forbid:
    - ^os.Exit$
    - ^panic$
    - ^print(ln)?$
    - ^unsafe\.
    - ^log\.
    - ^fmt\.(Printf|Scanf|Sprintf|Sscanf)$
