# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Test Release

on:
  pull_request:

jobs:
  goreleaser:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch tags
      run: git fetch --force --tags

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true

    - uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean --snapshot
