# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write
  packages: write
  # issues: write

jobs:
  goreleaser:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch tags
      run: git fetch --force --tags

    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    - uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
