# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Compliance Checks

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    name: REUSE
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v2
