# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    name: Test ${{ matrix.cgo && 'with' || 'without' }} Cgo
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cgo: [true, false]

    env:
      CGO_ENABLED: ${{ matrix.cgo && '1' || '0' }}

    steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: sudo apt-get install -y
        libsodium-dev
        libclang-dev
        pkg-config
        cmake
        ninja-build

    - name: Install rosenpass from git
      uses: baptiste0928/cargo-install@v2
      with:
        crate: rosenpass
        git: https://github.com/rosenpass/rosenpass
        commit: b29720b0c67ddf96f114c134bed076f27018313e

    - name: Checkout liboqs
      uses: actions/checkout@v3
      with:
        repository: open-quantum-safe/liboqs
        ref: 0.8.0
        path: liboqs
      if: ${{ matrix.cgo }}
  
    - name: Install liboqs
      run: |
        mkdir -p liboqs/build && cd liboqs/build
        cmake -GNinja \
          -DOQS_BUILD_ONLY_LIB=ON \
          -DOQS_MINIMAL_BUILD="KEM_kyber_512;KEM_classic_mceliece_460896" \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_INSTALL_PREFIX=/usr ..
        sudo ninja install
      if: ${{ matrix.cgo }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Set up gotestfmt
      run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

    - name: Run Go tests
      run: |
        set -euo pipefail
        go test -v \
          -json \
          -coverpkg ./... \
          -coverprofile cover.profile \
          ./... 2>&1 | \
        tee /tmp/gotest.log | \
        gotestfmt

    - name: Upload test log
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-log
        path: /tmp/gotest.log
        if-no-files-found: error

    - name: Report integration test coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: cover.profile
