# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Test

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: '0'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt-get install -y
        libsodium-dev
        libclang-dev
        pkg-config
        cmake
        ninja-build

    - name: Install rosenpass from git
      uses: baptiste0928/cargo-install@v2
      with:
        crate: rosenpass
        git: https://github.com/rosenpass/rosenpass
        tag: v0.2.0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Set up gotestfmt
      run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

    - name: Run Go tests
      run: |
        set -euo pipefail
        sudo --preserve-env \
          env "PATH=$PATH" \
          go test \
            -v \
            -json \
            -coverpkg ./... \
            -coverprofile cover.profile \
            ./... 2>&1 | \
        tee /tmp/gotest.log | \
        gotestfmt

    - name: Upload test log
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-log
        path: /tmp/gotest.log
        if-no-files-found: error

    - name: Report integration test coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: cover.profile
